language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
env:
  # Deployments are disabled by default
  - DEPLOY=false DEPLOY_DOCS=false
matrix:
  exclude:
    - jdk: oraclejdk7
    - jdk: oraclejdk8
  include:
    # Code artifacts deployed with JDK7
    - jdk: oraclejdk7
      env: DEPLOY=true DEPLOY_DOCS=false
    # Documentation deployed with JDK8
    - jdk: oraclejdk8
      env: DEPLOY=false DEPLOY_DOCS=true
    
before_install:
  # Sets the deployment flags
  - PULL_REQUEST=$TRAVIS_PULL_REQUEST
  # Sets the version type
  - VERSION_TYPE=other
  - if [ "$TRAVIS_BRANCH" == "master" ] ; then VERSION_TYPE=release; fi
  - if [ "$TRAVIS_BRANCH" == "develop" ] ; then VERSION_TYPE=develop; fi
  # Scripts are set as executable
  - chmod +x ./.scripts/create-maven-settings.sh
  - chmod +x ./.scripts/deploy.sh
  - chmod +x ./.scripts/deploy-site.sh
  # Creates Maven settings
  - ./.scripts/create-maven-settings.sh
script:
  # Unit, integration and archetype tests are run
  - mvn clean verify archetype:integration-test
after_success:
  # Documentation deployment script
  - ./.scripts/deploy-site.sh
  # Code artifacts deployment script
  - ./.scripts/deploy.sh
