language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
  - chmod +x ./.scripts/create-maven-settings.sh
  - chmod +x ./.scripts/deploy-site.sh
  - ./.scripts/create-maven-settings.sh
script:
  - mvn clean verify archetype:integration-test
  - install archetype:update-local-catalog
  - mvn archetype:generate -DgroupId=com.wadnrell -DartifactId=artifact -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
  - cd artifact
  - mvn clean verify site
after_success:
  - ./.scripts/deploy-site.sh
