name: Doc deployment

on:
  push:
    branches:
      - develop
      - master

jobs:
  deploy_docs:

    runs-on: ubuntu-latest

    steps:
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        ssh-keyscan -H docs.bernardomg.com >> ~/.ssh/known_hosts
      shell: bash
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Maven settings
      uses: bernardo-mg/deployment-maven-settings-action@master
      with:
        version-type: ${{ steps.extract_branch.outputs.branch }}
      env:
        DEPLOY_DOCS_USER: ${{ secrets.DEPLOY_DOCS_USER }}
        DEPLOY_DOCS_PASSWORD: ${{ secrets.DEPLOY_DOCS_PASSWORD }}
        DEPLOY_DOCS_DEVELOP_USER: ${{ secrets.DEPLOY_DOCS_DEVELOP_USER }}
        DEPLOY_DOCS_DEVELOP_PASSWORD: ${{ secrets.DEPLOY_DOCS_DEVELOP_PASSWORD }}
        DEPLOY_DOCS_SITE: ${{ secrets.DEPLOY_DOCS_SITE }}
        DEPLOY_DOCS_DEVELOP_SITE: ${{ secrets.DEPLOY_DOCS_DEVELOP_SITE }}
    - name: Deploy docs
      run: mvn site site:deploy -B -P deployment --settings settings.xml
