name: Tests and docs

on: [push, pull_request]

jobs:
  tests:
    name: Tests with JDK ${{ matrix.jdk }}
    strategy:
      matrix:
        jdk: [ 11, 17 ]
    uses: Bernardo-MG/github-workflow-maven/.github/workflows/testing.yml@v1
    with:
      jdk: ${{ matrix.jdk }}

  deploy_docs:
    name: Deploy development docs
    strategy:
      matrix:
        include:
          - branch: develop
            url: DEPLOY_DOCS_DEVELOP_SITE
            username: DEPLOY_DOCS_DEVELOP_USER
            password: DEPLOY_DOCS_DEVELOP_PASSWORD
          - branch: master
            url: DEPLOY_DOCS_SITE
            username: DEPLOY_DOCS_USER
            password: DEPLOY_DOCS_PASSWORD
    needs: tests
    uses: Bernardo-MG/github-workflow-maven/.github/workflows/deploy_site.yml@v1
    with:
      branch: ${{ matrix.branch }}
      host: docs.bernardomg.com
    secrets:
      url: ${{ secrets[matrix.url] }}
      username: ${{ secrets[matrix.username] }}
      password: ${{ secrets[matrix.password] }}
